services:
  backend:
    build: ./backend
    container_name: xdotcontractor_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db/xdotcontractor_db
      - SECRET_KEY=your_secret_key
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: xdotcontractor_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: xdotcontractor_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: xdotcontractor_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: